services:

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - aic
  
  ai:
    build:
      context: ./ai-backend
      dockerfile: dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    env_file:
      - ./ai-backend/.env
    networks:
      - aic

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - aic


networks:
  aic:
    driver: bridge